#!usr/env/bin php

<?php

require_once __DIR__.'/../../vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Console\SpeakCommand;

$app = new Application;

$app->add(new SpeakCommand);

$app->run();